[build]
   publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/ai-diagnostic-engine"
  to = "/.netlify/functions/ai-diagnostic-engine"
  status = 200

[[redirects]]
  from = "/api/ai-quiz"
  to = "/.netlify/functions/ai-quiz"
  status = 200

[[redirects]]
  from = "/api/ai-intake-agent"
  to = "/.netlify/functions/ai-intake-agent"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
